apiVersion: v1
kind: ConfigMap
metadata:
  name: boringtun
data:
  wg0.conf: |-
    [Interface]
    Address = 10.192.0.1/24
    PrivateKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    ListenPort = 8080
    PreUp = echo "1" > /proc/sys/net/ipv4/ip_forward
    PostUp = iptables-legacy -t nat -A POSTROUTING -o eth0 -s 10.192.0.0/24 -j MASQUERADE

    [Peer]
    PublicKey = yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    AllowedIPs = 10.192.0.2/32

    [Peer]
    PublicKey = zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
    AllowedIPs = 10.192.0.3/32
